### ISSUE TITLE
Font Awesome CSS rules are not valid for some elements

### ISSUE THREAD

**Issue by fallenflint** [d-demirci/django-adminlte3#10]
Hey, thanks for your project!

But I found that you have a lot of `class="far ...blah-blah-blah"` , and it produces a strange error - add button on each and every admin page has blank rectangle instead of plus sign.
This is because of far styling is available only for pro version of the font (according to https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use). As well as fal and fad.
The short search shows that there are a huge amount of far occurances on the project.

Chances I will have time to fix it by myself if you're going to accept that via pull request. But it's not certain.

**Comment by d-demirci** [comment]
with this 9c1faec81a040580e4fd1ebe517b0a2cd67a0f42 I replaced the icons which is available when using pro version of fontawesome with the solid ones (fas). Some of the far classes in fontawesome can be used in free version, the results in your search comes from adminlte base template ( which are also available in free version of fontawesome). Hope this  commit will clean those blank rectangle signs.
