### ISSUE TITLE
inline forms don't seem to render as expected

### ISSUE THREAD

**Issue by d-demirci** [d-demirci/django-adminlte3#15]
<img width="1091" alt="Screen Shot 2020-04-16 at 01 12 37" src="https://user-images.githubusercontent.com/24219129/79394118-67f67280-7f7f-11ea-8c53-26b4b30cc04b.png">

**Comment by vsmay98** [comment]
Yes, same issue with me. Can someone help me with this
![image](https://user-images.githubusercontent.com/32728207/81779460-64b8bd00-9512-11ea-810d-fff4d96a668b.png)

@d-demirci  Did you find any solution? Any help will be appreciated

**Comment by navi380** [comment]
i use StackedInline instead of TabularInline its look good and solve my issue for now. but its a big problem kindly solve it. problem is in the table creation it add a column(td) with class original or something like that which distract the whole table.
