### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by craph** [d-demirci/django-adminlte3#6]
Hi,

Your demo site on heroku seems KO : https://django-adminlte3.herokuapp.com/

![image](https://user-images.githubusercontent.com/14820052/71896616-8a911800-3154-11ea-8bee-34ca322c4f79.png)

**Comment by d-demirci** [comment]
Ok I will check it later today. Thanks for feedback.

**Comment by craph** [comment]
Hello @d-demirci ,

Did you had the time to check it ?

**Comment by d-demirci** [comment]
you can use https://django-adminlte3.herokuapp.com/admin for now to see admin interface
username : username
password : pazzworth
